# Generated by Django 4.2.12 on 2024-05-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_name"),
        ("lots", "0003_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="category",
            field=models.ForeignKey(
                default="boards",
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
            ),
        ),
    ]
