# Generated by Django 4.2.13 on 2024-05-29 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots', '0005_alter_watchlist_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='item',
            new_name='lot',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('owner', 'lot')},
        ),
    ]
