# Generated by Django 4.2.13 on 2024-05-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_rename_bid_amount_bid_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='amount',
            new_name='bid_amount',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='time',
            new_name='created_at',
        ),
    ]
