# Generated by Django 4.2.13 on 2024-05-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lots", "0007_rename_amount_bid_bid_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lots.lot"
            ),
        ),
    ]
