# Generated by Django 4.2.13 on 2024-06-04 16:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("lots", "0008_rename_user_comment_author_alter_watchlist_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lot",
            name="finished_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
