# Generated by Django 4.2.13 on 2024-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lots", "0010_lot_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="winner",
        ),
        migrations.AddField(
            model_name="bid",
            name="winner",
            field=models.BooleanField(default=False),
        ),
    ]
