# Generated by Django 4.2.7 on 2023-12-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Boards", "Boards"),
                            ("Attachment", "Attachment"),
                            ("Boots", "Boots"),
                            ("Clothing", "Clothing"),
                            ("Tools", "Tools"),
                            ("Other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
