# Generated by Django 4.2.12 on 2024-05-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("boards", "Boards"),
                    ("attachment", "Attachment"),
                    ("boots", "Boots"),
                    ("clothing", "Clothing"),
                    ("tools", "Tools"),
                    ("other", "Other"),
                ],
                max_length=64,
            ),
        ),
    ]
