# Generated by Django 4.2.13 on 2024-08-21 13:31

from django.db import migrations
import yeticave.users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_follow"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", yeticave.users.managers.UserManager()),
            ],
        ),
    ]
