# Generated by Django 4.2.13 on 2024-06-06 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lots", "0012_rename_winner_bid_is_winner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lot",
            old_name="starting_bid",
            new_name="starting_price",
        ),
        migrations.AlterField(
            model_name="lot",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_lost",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
