# Generated by Django 4.2.13 on 2024-07-01 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lots", "0018_commentreaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentreaction",
            old_name="reaction",
            new_name="reaction_type",
        ),
    ]
