# Generated by Django 4.2.13 on 2024-08-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_name"),
        ("lots", "0020_alter_lot_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categories.category"
            ),
        ),
    ]
