# Generated by Django 4.2.12 on 2024-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lots", "0002_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Comment"),
        ),
    ]
