# Generated by Django 4.2.13 on 2024-06-04 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lots", "0009_lot_created_at_lot_finished_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_lots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
