# Generated by Django 4.2.13 on 2024-06-04 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lots", "0011_remove_lot_winner_bid_winner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="winner",
            new_name="is_winner",
        ),
    ]
