# Generated by Django 4.2.13 on 2024-06-07 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_followers_remove_user_following_follow"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
